services:
  - type: web
    name: nasa-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NASA_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
    rootDir: backend
  - services:
  - type: staticSite
    name: nasa-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDirectory: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://galactic-twilight.onrender.com