services:
  - type: web
    name: nasa-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NASA_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
    rootDir: backend
  - type: staticSite
    name: nasa-frontend
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    publishDirectory: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService: nasa-backend
